- name: setup laptop
  groups:
  - local
  - servers
  pre:
   - !shell
     name: pe-tasks
     cmd: "echo running pre-tasks"
  roles:
    - role: test
  post:
   - !shell
     name: post-tasks
     cmd: "echo running post-tasks"
