---
- name: setup laptop
  groups:
    - local
    - servers
  vars:
    playbook_var_1: playbook_var_1
    playbook_var_2: playbook_var_2
    playbook_var_3: playbook_var_3
  pre:
   - !shell
     name: pre task {{ .playbook_var_1 }}
     cmd: "echo doing some pre tasks"
  roles:
    - role: test
  post:
   - !shell
     name: post tasks
     cmd: "echo doing some post tasks"
