---
local:
    env:
      test: hi
      test2: bye
servers:
  hosts:
    - 192.168.60.20
    - 192.168.60.25
  development:
    hosts: 192.168.60.10
    vars:
      server1_var: hi
    env:
      DEVELOPMENT_ENV_KEY: DEVELOPMENT_ENV_VALUE
  staging:
    hosts:
      - 192.168.60.10
      - 192.168.60.11
    pre-staging:
      hosts:
        - 192.168.60.5
    post-staging:
      hosts:
        - 192.168.60.5
      env:
        POST-STAGING_ENV_KEY: POST-STAGING_ENV_VALUE
    vars:
      test: bye
    env:
      STAGING_ENV_KEY: STAGING_ENV_VALUE
  production:
    hosts:
      - 192.168.60.10
      - 192.168.60.11:
          env:
            server3_host_2_env: hi
      - 192.168.60.4
    vars:
      servers_var1: smahm
      servers_var2: 1234
    env:
      PRODUCTION_ENV_KEY: PRODUCTION_ENV_VALUE
