---
local:
    env:
      test: hi
      test2: bye
servers:
  vars:
      gear_ssh_user: vagrant
      gear_ssh_private_key: /home/smahm/workstation/architecture/virtualmachines/vagrant/insecure_private_key
  development:
    hosts: 192.168.121.186
    vars:
      server1_var: hi
    env:
      DEVELOPMENT_ENV_KEY: DEVELOPMENT_ENV_VALUE
  staging:
    hosts:
      - 192.168.121.229
    vars:
      test: bye
    env:
      STAGING_ENV_KEY: STAGING_ENV_VALUE
  production:
    hosts:
      - 192.168.121.73
    vars:
      servers_var1: smahm
      servers_var2: 1234
    env:
      PRODUCTION_ENV_KEY: PRODUCTION_ENV_VALUE
